### ISSUE TITLE
Unlock account should be in the transaction node console not 

### ISSUE THREAD

**Issue by ujjwalmsft** [michael-chi/ethereumsupplychain#1]
Unlock account should be in the transaction node console not truffle console.

Current document in readme file shows unlock account in truffle node command prompt which shows error.

web3.personal.unlockAccount(web3.eth.accounts[0],!|\<YOUR ETHEREUM ACCOUNT PASSWORD\>!|);

**Comment by michael-chi** [comment]
updated in PR #2
